version: '2'

services:
  
  password-api-1:
    # using images to build it
    image: nicopaez/password-api
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8001/health"]
      interval: 5s
      retries: 5
    ports:
        - "8001:3000"

  password-api-2:
    # using internal docker file to build it
    image: nicopaez/password-api
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:8002/health"]
      interval: 5s
      retries: 5
    ports:
        - "8002:3000"

  nginx:
    build: ./nginx
    ports:
      - "8090:80"
    depends_on:
    - password-api-1
    - password-api-2